### ISSUE TITLE
Maven build step of "Run CI" GitHub action could not handle source branches with '/' in the name

### ISSUE THREAD

**Issue by tdddblog** [NASA-PDS/registry-ci#2]
## 🐛 Describe the bug
Maven build step in CI test could not handle source branches with '/' in the name, for example branch `release/v0.3`, see
`https://github.com/NASA-PDS/registry-api-service/runs/3163966969?check_suite_focus=true`

## 📜 To Reproduce
1. Trigger `Run CI` action on branch with '/' in the name, such as `test/123`
4. See an error similar to this `error: pathspec '123' did not match any file(s) known to git`

## 🕵️ Expected behavior
"Run CI" GitHub action should work with branches containing '/' in the name

**Comment by jordanpadams** [comment]
closed per https://github.com/NASA-PDS/registry-ci/pull/3
